language: php
dist: bionic
os: linux
addons:
  apt:
    packages:
      - cmake
      - debhelper
      - devscripts
      - dh-exec
      - fakeroot
      - libssl-dev
      - libuv1-dev
      - openjdk-8-jdk-headless
cache:
  ccache: true
  directories:
    - ${HOME}/dependencies
php:
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    # Configure the quality assurance tests to be TravisCI friendly
    - REPORT_EXIT_STATUS=1
    - TEST_PHP_ARGS="-q -s output.txt -g XFAIL,FAIL,BORK,WARN,LEAK,SKIP -x --show-diff"
    # Add the pip installation folder to the PATH, until https://github.com/travis-ci/travis-ci/issues/3563 is fixed
    - PATH=${HOME}/.local/bin:${PATH}
    # Indicate the cached dependencies directory
    - CACHED_DEPENDENCIES_DIRECTORY=${HOME}/dependencies
    # Add DataStax C/C++ driver packages for cacheing
    - PHP_DRIVER_BUILD_DIRECTORY=/tmp/php-driver/build
    - CPP_DRIVER_SOURCE_DIRECTORY=${TRAVIS_BUILD_DIR}/lib/cpp-driver
    - CPP_DRIVER_BUILD_DIRECTORY=${PHP_DRIVER_BUILD_DIRECTORY}/cpp-driver
    # Add JAVA_HOME for non-java projects
    - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    - PATH=${JAVA_HOME}/bin:${PATH}
    # BEHAT integration configuration settings
    - BEHAT_EXTRA_OPTIONS=
    - BEHAT_SKIP_TAGS=~@skip-ci

before_install:
  # Get the DataStax C/C++ driver version
  - export CPP_DRIVER_VERSION_MAJOR=$(grep CASS_VERSION_MAJOR ${CPP_DRIVER_SOURCE_DIRECTORY}/include/cassandra.h | sed 's/[^0-9]*//g')
  - export CPP_DRIVER_VERSION_MINOR=$(grep CASS_VERSION_MINOR ${CPP_DRIVER_SOURCE_DIRECTORY}/include/cassandra.h | sed 's/[^0-9]*//g')
  - export CPP_DRIVER_VERSION_PATCH=$(grep CASS_VERSION_PATCH ${CPP_DRIVER_SOURCE_DIRECTORY}/include/cassandra.h | sed 's/[^0-9]*//g')
  - export CPP_DRIVER_VERSION=${CPP_DRIVER_VERSION_MAJOR}.${CPP_DRIVER_VERSION_MINOR}.${CPP_DRIVER_VERSION_PATCH}

  # Get the SHA and construct the cached directory for the DataStax C/C++ driver packages
  - (
      cd lib/cpp-driver;
      export CPP_DRIVER_VERSION_SHA=$(git rev-parse --short HEAD);
    )
  - export CPP_DRIVER_CACHED_DIRECTORY=${CACHED_DEPENDENCIES_DIRECTORY}/cpp-driver/${CPP_DRIVER_VERSION}/${CPP_DRIVER_VERSION_SHA}

  # Determine if the DataStax C/C++ driver should be built
  - if [ ! -d "${CPP_DRIVER_CACHED_DIRECTORY}" ]; then
    (
      cd ${CPP_DRIVER_SOURCE_DIRECTORY}/packaging;
      ./build_deb.sh;
      mkdir -p ${CPP_DRIVER_CACHED_DIRECTORY};
      find build -type f -name "*.deb" -exec mv {} ${CPP_DRIVER_CACHED_DIRECTORY} \;;
    )
    else echo "Using Cached C/C++ driver v${CPP_DRIVER_VERSION}-${CPP_DRIVER_VERSION_SHA}. Dependency does not need to be re-compiled";
    fi;

  # Install the DataStax C/C++ driver
  - sudo dpkg -i ${CPP_DRIVER_CACHED_DIRECTORY}/*

install:
  # Prepare the build environment for the PHP extension
  - (
      cd ${TRAVIS_BUILD_DIR}/ext;
      phpize;
    )

  # Configure, build, install, and enable the DataStax PHP driver
  - mkdir -p ${PHP_DRIVER_BUILD_DIRECTORY}
  - (
      cd ${PHP_DRIVER_BUILD_DIRECTORY};
      ${TRAVIS_BUILD_DIR}/ext/configure;
      make -j$(nproc) install;
      echo "extension=cassandra.so" >> $(php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||");
    )

before_script:
  # Update composer and install the test dependencies
  - composer self-update
  - composer install -n

script:
  # Execute the quality assurance tests
  - (
      cd ${PHP_DRIVER_BUILD_DIRECTORY};
      make test;
    )

  # Execute the unit tests
  - ./bin/phpunit --testsuite unit

  # Execute the examples/tests using Behat and the latest version of Apache Cassandra (master branch only)
  - if [ "${TRAVIS_BRANCH}" = "master" ]; then
      pip install --user ccm;
      ./bin/behat --tags="${BEHAT_SKIP_TAGS}" ${BEHAT_EXTRA_OPTIONS};
    fi;
