name: build
on:
  pull_request:
  push:
    branches:
      - master
env:
  BUILDKIT_PROGRESS: plain
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: make
